version: '3.8'

services:
  newsbreeze:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static/audio:/app/static/audio
      - ./static/voices:/app/static/voices
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - newsbreeze
  #   restart: unless-stopped 